### ISSUE TITLE
Better birthday parsing for incompetent humans

### ISSUE THREAD

**Issue by AdriBloober** [AdriBloober/DiscordBirthdayBot#21]
Some humans can't read help. These peoples need easier birthday parsing.

Birthday parsing for:
- Day-Month
- Day Month

**Comment by Floxiii** [comment]
Please add DayMonth like 1508 :)

**Comment by AdriBloober** [comment]
Please add the birthday in seconds multiplied with the time since the second birthday of Floxiii.

**Comment by Floxiii** [comment]
Please insert international formats, such as (2020)-08-17

**Comment by AdriBloober** [comment]
The birthday bot does not support the year of the birthday.
The syntax Month-Day is invalid.
